Setup mobile version
Mucyosoda/setup-and-mobile-version-skeleton pull request #1
Opened 2021-08-12 12:36 UTC by Mucyosoda

2021-08-12 14:38 UTC, Murodjon000 requested changes
**Hi, Claude Mucyo** 👋, 

Good job so far!

### To Highlight 🎉
- The project is very well structured😃😃
- The mobile version is working as expected
- You have mastered GitHub flow

But there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] It would be better if you change the design of your mobile headline page section because the one you implemented is different from the design in [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471).
-  The design you did is this.
![ ](https://res.cloudinary.com/dflkwvvnz/image/upload/v1628778374/scrnli_8_12_2021_6-58-05_PM_bksytt.png)

- If you saw the Figma design, there are some changes you should do in your project. Especially in the introduction section, your text styling is not like the given design and gives some height to your icons to make them fancy. 

- _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Try to make our readme template by using the Microverse template and reuse it in your all projects. Then you will never think about your readme file.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 14:38 UTC, Murodjon000 commented on README.md
>  - Major languages
- [ ] It would be fine if you remove this line because it is the direction for you. Instead of this, you should write the languages you used 😃.

2021-08-13 17:08 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Mucyo Ntacyonungutse, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
- [x] Linter is working fine.
- [x] README is professional.

## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-13 17:08 UTC, SajjadAhmad14 commented on index.html
> +      </ul>
Please add proper spacing between icons on the mobile header. KIndly follow exact margin and padding from design.

2021-08-13 18:02 UTC, Emmyn5600 approved these changes
## STATUS: APPROVED :muscle::clap:

Hi, @Mucyosoda 

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous code reviewers. Kudos
   
#### Optional suggestions
Your commits should be in present tense and clear to everyone, I wonder why you kept using update for all commits you did.

![commit](https://user-images.githubusercontent.com/55635977/129400527-4f5c0cb7-e878-4d12-99c4-535550b454f2.png)

You need to use past tense for the descriptive PR as well.

![commit1](https://user-images.githubusercontent.com/55635977/129400628-880c2c89-381f-4c22-9889-7a15b44d1b75.png)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-16 09:44 UTC, merged