Desktop version
Mucyosoda/setup-and-mobile-version-skeleton pull request #5
Opened 2021-08-20 08:17 UTC by Mucyosoda

Desktop version  and responsive 

-  Added index.html
- Added style.css
- Added linters
- Added gitignore
- Added readme file

2021-08-20 09:27 UTC, mke2111 requested changes
### Hey @Mucyosoda,

**This is a great project you have going on, well-done lad**. 

   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-20 09:31 UTC, mke2111 commented on index.html
> +          <div class="post1">
- [ ] For this section, align both the left and right sides to the top.
![Screenshot from 2021-08-20 12-28-55](https://user-images.githubusercontent.com/65501535/130212842-efdb0696-254d-4195-8c83-10f86708a6fd.png)

2021-08-20 09:35 UTC, mke2111 commented on index.html
> +        <div id="content_one">
- [ ] The about section is being overflowed by the projects section. Give it a fix.

2021-08-20 09:39 UTC, mke2111 commented on index.html
> +        <div class="cards_room">
![Screenshot from 2021-08-20 12-37-06](https://user-images.githubusercontent.com/65501535/130213806-1c1fc97e-b265-4916-a620-90043f50d3c6.png)

2021-08-20 09:42 UTC, mke2111 commented on index.html
> +          <div class="content_3">
![Screenshot from 2021-08-20 12-37-06](https://user-images.githubusercontent.com/65501535/130213806-1c1fc97e-b265-4916-a620-90043f50d3c6.png)

2021-08-20 09:44 UTC, mke2111 commented on index.html
> +        <div class="form_view">
- [ ] This section should cover the entire space and equal the section above.
![Screenshot from 2021-08-20 12-43-56](https://user-images.githubusercontent.com/65501535/130214609-8ed21d6a-cd3b-4b82-9de8-71c6473b76f4.png)

2021-08-20 09:47 UTC, mke2111 commented on style.css
> +@media only screen and (min-width: 768px) {
- [ ] The value for min-width property should be in range of 992px - 1100px. These are the accepted desktop screen breakpoints. Change your value. What you are using lies under the tablet screen breakpoints.

2021-08-20 09:50 UTC, mke2111 commented on style.css
> +form {
- [ ] For mobile screen sizes, I believe a bug has been introduced while working on the desktop version. The contact form display has been altered for mobile screens.
![Screenshot from 2021-08-20 12-48-29](https://user-images.githubusercontent.com/65501535/130215349-9f3bf895-3d37-4f98-8b6b-e9a272a4351d.png)

2021-08-20 12:37 UTC, mke2111 requested changes
### Hey @Mucyosoda, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-20 12:40 UTC, mke2111 commented on index.html
> +          <div class="post1">
> For this section, align both the left and right sides to the top.
![Screenshot from 2021-08-20 12-28-55](https://user-images.githubusercontent.com/65501535/130212842-efdb0696-254d-4195-8c83-10f86708a6fd.png)

Please consider aligning this section as previously requested.

2021-08-20 12:41 UTC, mke2111 commented on index.html
> +          <div class="content_3">
> The about section is being overflowed by the projects section. Give it a fix.
![Screenshot from 2021-08-20 12-37-06](https://user-images.githubusercontent.com/65501535/130213806-1c1fc97e-b265-4916-a620-90043f50d3c6.png)

Please consider fixing the overflow issue

2021-08-20 12:43 UTC, mke2111 commented on index.html
> +        <div class="form_view">
> This section should cover the entire space and equal the section above.
![Screenshot from 2021-08-20 12-43-56](https://user-images.githubusercontent.com/65501535/130214609-8ed21d6a-cd3b-4b82-9de8-71c6473b76f4.png)

Please consider stretching out this section to fit and match the other sections. Focus mainly on its padding/margin

2021-08-21 09:44 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Mucyo Ntacyonungutse, , 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
# OPTIONAL
- [ ] Please see inline comments.
## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-21 09:44 UTC, SajjadAhmad14 commented on index.html
>    <body>
[OPTIONAL] Please remove space from the right and left of the page and follow the design exactly. Kindly see the below screenshot for reference. 
![space](https://user-images.githubusercontent.com/35504149/130317844-cd14c624-d63b-46b2-8c16-f92a0af72f15.png)

2021-08-21 09:44 UTC, SajjadAhmad14 commented on index.html
> +        <div class="logo">LOGO</div>
[ OPTIONAL ] Please align navigation items vertically, and use the font which is defined in the design. Kindly see the below screenshot for reference.
![heading](https://user-images.githubusercontent.com/35504149/130317832-bb47b318-d0ab-4468-90f3-f535bd039f13.png)

2021-08-21 09:44 UTC, SajjadAhmad14 commented on index.html
> -        </p>
[ OPTIONAL ] Please follow the font color and font family defined in the design.

2021-08-21 09:44 UTC, SajjadAhmad14 commented on index.html
> +          </ul>
[ OPTIONAL ] Please follow the font color and font family defined in the design.

2021-08-21 09:44 UTC, SajjadAhmad14 commented on index.html
> +        </div>
[ OPTIONAL ] Please follow the font family defined in the design.

2021-08-31 14:11 UTC, merged